spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: iglrgkmweibcpruh
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: hhiep1hk@gmail.com
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:
            scope:
            - email
            - profile
#          facebook:
#            clientId: 
#            clientSecret: 
#            scope:
#            - email
#            - public_profile

google:
  app:
    id: 
    secret: 
  redirect:
    uri: http://localhost:8080/login-google
  link:
    get:
      token: https://accounts.google.com/o/oauth2/token
      user_info: https://www.googleapis.com/oauth2/v1/userinfo?access_token=
    
facebook:
  app:
    id: 
    secret: 
  redirect:
    uri: http://localhost:8080/login-facebook
  link:
    get:
      token: https://graph.facebook.com/oauth/access_token?client_id=%s&client_secret=%s&redirect_uri=%s&code=%s
      user_info: https://graph.facebook.com/me?fields=id,name,email,picture&access_token=
    
    
    
    
